// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Agreement.proto

package via.sep3.group11.tier3.protobuf;

public final class AgreementOuterClass {
  private AgreementOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GAgreementList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GAgreementList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Agreement.proto\032\024SharedMessages.proto\"" +
      "1\n\016GAgreementList\022\037\n\nagreements\030\001 \003(\0132\013." +
      "GAgreement2\303\002\n\tAgreement\022(\n\014addAgreement" +
      "\022\013.GAgreement\032\013.GAgreement\022+\n\017updateAgre" +
      "ement\022\013.GAgreement\032\013.GAgreement\022%\n\020getAg" +
      "reementById\022\004.GId\032\013.GAgreement\0220\n\024getAgr" +
      "eementByHostId\022\007.GEmail\032\017.GAgreementList" +
      "\022 \n\017deleteAgreement\022\004.GId\032\007.GEmpty\0223\n\032ge" +
      "tAllAgreementByHousingId\022\004.GId\032\017.GAgreem" +
      "entList\022/\n\027getAgreementByRefugeeId\022\007.GEm" +
      "ail\032\013.GAgreementB#\n\037via.sep3.group11.tie" +
      "r3.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.sep3.group11.tier3.protobuf.SharedMessages.getDescriptor(),
        });
    internal_static_GAgreementList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GAgreementList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GAgreementList_descriptor,
        new java.lang.String[] { "Agreements", });
    via.sep3.group11.tier3.protobuf.SharedMessages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
