// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SharedMessages.proto

package via.sep3.group11.tier3.protobuf;

public interface GAddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GAddress)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country = 1;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 1;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string streetName = 3;</code>
   * @return The streetName.
   */
  java.lang.String getStreetName();
  /**
   * <code>string streetName = 3;</code>
   * @return The bytes for streetName.
   */
  com.google.protobuf.ByteString
      getStreetNameBytes();

  /**
   * <code>string houseNumber = 4;</code>
   * @return The houseNumber.
   */
  java.lang.String getHouseNumber();
  /**
   * <code>string houseNumber = 4;</code>
   * @return The bytes for houseNumber.
   */
  com.google.protobuf.ByteString
      getHouseNumberBytes();

  /**
   * <code>string roomNumber = 5;</code>
   * @return The roomNumber.
   */
  java.lang.String getRoomNumber();
  /**
   * <code>string roomNumber = 5;</code>
   * @return The bytes for roomNumber.
   */
  com.google.protobuf.ByteString
      getRoomNumberBytes();

  /**
   * <code>string postCode = 6;</code>
   * @return The postCode.
   */
  java.lang.String getPostCode();
  /**
   * <code>string postCode = 6;</code>
   * @return The bytes for postCode.
   */
  com.google.protobuf.ByteString
      getPostCodeBytes();

  /**
   * <code>int64 id = 7;</code>
   * @return The id.
   */
  long getId();
}
