// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Housing.proto

package via.sep3.group11.tier3.protobuf;

public interface GAddHousingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GAddHousingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.GHousing housing = 1;</code>
   * @return Whether the housing field is set.
   */
  boolean hasHousing();
  /**
   * <code>.GHousing housing = 1;</code>
   * @return The housing.
   */
  via.sep3.group11.tier3.protobuf.GHousing getHousing();
  /**
   * <code>.GHousing housing = 1;</code>
   */
  via.sep3.group11.tier3.protobuf.GHousingOrBuilder getHousingOrBuilder();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
