// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SharedMessages.proto

package via.sep3.group11.tier3.protobuf;

public interface GAgreementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GAgreement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.GDateOfBirth dateOfCreation = 2;</code>
   * @return Whether the dateOfCreation field is set.
   */
  boolean hasDateOfCreation();
  /**
   * <code>.GDateOfBirth dateOfCreation = 2;</code>
   * @return The dateOfCreation.
   */
  via.sep3.group11.tier3.protobuf.GDateOfBirth getDateOfCreation();
  /**
   * <code>.GDateOfBirth dateOfCreation = 2;</code>
   */
  via.sep3.group11.tier3.protobuf.GDateOfBirthOrBuilder getDateOfCreationOrBuilder();

  /**
   * <code>.GHostDetails hostDetails = 3;</code>
   * @return Whether the hostDetails field is set.
   */
  boolean hasHostDetails();
  /**
   * <code>.GHostDetails hostDetails = 3;</code>
   * @return The hostDetails.
   */
  via.sep3.group11.tier3.protobuf.GHostDetails getHostDetails();
  /**
   * <code>.GHostDetails hostDetails = 3;</code>
   */
  via.sep3.group11.tier3.protobuf.GHostDetailsOrBuilder getHostDetailsOrBuilder();

  /**
   * <code>.GHousingWithStatus housing = 4;</code>
   * @return Whether the housing field is set.
   */
  boolean hasHousing();
  /**
   * <code>.GHousingWithStatus housing = 4;</code>
   * @return The housing.
   */
  via.sep3.group11.tier3.protobuf.GHousingWithStatus getHousing();
  /**
   * <code>.GHousingWithStatus housing = 4;</code>
   */
  via.sep3.group11.tier3.protobuf.GHousingWithStatusOrBuilder getHousingOrBuilder();

  /**
   * <code>.GRefugee refugee = 5;</code>
   * @return Whether the refugee field is set.
   */
  boolean hasRefugee();
  /**
   * <code>.GRefugee refugee = 5;</code>
   * @return The refugee.
   */
  via.sep3.group11.tier3.protobuf.GRefugee getRefugee();
  /**
   * <code>.GRefugee refugee = 5;</code>
   */
  via.sep3.group11.tier3.protobuf.GRefugeeOrBuilder getRefugeeOrBuilder();

  /**
   * <code>bool status = 6;</code>
   * @return The status.
   */
  boolean getStatus();
}
