// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Housing.proto

package via.sep3.group11.tier3.protobuf;

public interface GListOfHousingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GListOfHousing)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GHousingWithStatus housings = 1;</code>
   */
  java.util.List<via.sep3.group11.tier3.protobuf.GHousingWithStatus> 
      getHousingsList();
  /**
   * <code>repeated .GHousingWithStatus housings = 1;</code>
   */
  via.sep3.group11.tier3.protobuf.GHousingWithStatus getHousings(int index);
  /**
   * <code>repeated .GHousingWithStatus housings = 1;</code>
   */
  int getHousingsCount();
  /**
   * <code>repeated .GHousingWithStatus housings = 1;</code>
   */
  java.util.List<? extends via.sep3.group11.tier3.protobuf.GHousingWithStatusOrBuilder> 
      getHousingsOrBuilderList();
  /**
   * <code>repeated .GHousingWithStatus housings = 1;</code>
   */
  via.sep3.group11.tier3.protobuf.GHousingWithStatusOrBuilder getHousingsOrBuilder(
      int index);
}
