// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SharedMessages.proto

package via.sep3.group11.tier3.protobuf;

public interface GEmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GEmpty)
    com.google.protobuf.MessageOrBuilder {
}
