// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Housing.proto

package via.sep3.group11.tier3.protobuf;

public final class HousingOuterClass {
  private HousingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GAddHousingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GAddHousingRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rHousing.proto\032\024SharedMessages.proto\"?\n" +
      "\022GAddHousingRequest\022\032\n\007housing\030\001 \001(\0132\t.G" +
      "Housing\022\r\n\005email\030\002 \001(\t27\n\007Housing\022,\n\nadd" +
      "Housing\022\023.GAddHousingRequest\032\t.GHousingB" +
      "#\n\037via.sep3.group11.tier3.protobufP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.sep3.group11.tier3.protobuf.SharedMessages.getDescriptor(),
        });
    internal_static_GAddHousingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GAddHousingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GAddHousingRequest_descriptor,
        new java.lang.String[] { "Housing", "Email", });
    via.sep3.group11.tier3.protobuf.SharedMessages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
