// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Housing.proto

package via.sep3.group11.tier3.protobuf;

public interface ListOfAvailableHousingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListOfAvailableHousing)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GHousing housings = 1;</code>
   */
  java.util.List<via.sep3.group11.tier3.protobuf.GHousing> 
      getHousingsList();
  /**
   * <code>repeated .GHousing housings = 1;</code>
   */
  via.sep3.group11.tier3.protobuf.GHousing getHousings(int index);
  /**
   * <code>repeated .GHousing housings = 1;</code>
   */
  int getHousingsCount();
  /**
   * <code>repeated .GHousing housings = 1;</code>
   */
  java.util.List<? extends via.sep3.group11.tier3.protobuf.GHousingOrBuilder> 
      getHousingsOrBuilderList();
  /**
   * <code>repeated .GHousing housings = 1;</code>
   */
  via.sep3.group11.tier3.protobuf.GHousingOrBuilder getHousingsOrBuilder(
      int index);
}
