// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Agreement.proto

package via.sep3.group11.tier2.protobuf;

public final class AgreementOuterClass {
  private AgreementOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Agreement.proto\032\024SharedMessages.proto2" +
      "\267\001\n\tAgreement\022(\n\014addAgreement\022\013.GAgreeme" +
      "nt\032\013.GAgreement\022+\n\017updateAgreement\022\013.GAg" +
      "reement\032\013.GAgreement\022%\n\020getAgreementById" +
      "\022\004.GId\032\013.GAgreement\022,\n\024getAgreementByHos" +
      "tId\022\007.GEmail\032\013.GAgreementB#\n\037via.sep3.gr" +
      "oup11.tier2.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.sep3.group11.tier2.protobuf.SharedMessages.getDescriptor(),
        });
    via.sep3.group11.tier2.protobuf.SharedMessages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
