// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Housing.proto

package via.sep3.group11.tier2.protobuf;

/**
 * Protobuf type {@code GAddHousingRequest}
 */
public final class GAddHousingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GAddHousingRequest)
    GAddHousingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GAddHousingRequest.newBuilder() to construct.
  private GAddHousingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GAddHousingRequest() {
    email_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GAddHousingRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GAddHousingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            via.sep3.group11.tier2.protobuf.GHousing.Builder subBuilder = null;
            if (housing_ != null) {
              subBuilder = housing_.toBuilder();
            }
            housing_ = input.readMessage(via.sep3.group11.tier2.protobuf.GHousing.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(housing_);
              housing_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.group11.tier2.protobuf.HousingOuterClass.internal_static_GAddHousingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.group11.tier2.protobuf.HousingOuterClass.internal_static_GAddHousingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.group11.tier2.protobuf.GAddHousingRequest.class, via.sep3.group11.tier2.protobuf.GAddHousingRequest.Builder.class);
  }

  public static final int HOUSING_FIELD_NUMBER = 1;
  private via.sep3.group11.tier2.protobuf.GHousing housing_;
  /**
   * <code>.GHousing housing = 1;</code>
   * @return Whether the housing field is set.
   */
  @java.lang.Override
  public boolean hasHousing() {
    return housing_ != null;
  }
  /**
   * <code>.GHousing housing = 1;</code>
   * @return The housing.
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GHousing getHousing() {
    return housing_ == null ? via.sep3.group11.tier2.protobuf.GHousing.getDefaultInstance() : housing_;
  }
  /**
   * <code>.GHousing housing = 1;</code>
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GHousingOrBuilder getHousingOrBuilder() {
    return getHousing();
  }

  public static final int EMAIL_FIELD_NUMBER = 2;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (housing_ != null) {
      output.writeMessage(1, getHousing());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (housing_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHousing());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.group11.tier2.protobuf.GAddHousingRequest)) {
      return super.equals(obj);
    }
    via.sep3.group11.tier2.protobuf.GAddHousingRequest other = (via.sep3.group11.tier2.protobuf.GAddHousingRequest) obj;

    if (hasHousing() != other.hasHousing()) return false;
    if (hasHousing()) {
      if (!getHousing()
          .equals(other.getHousing())) return false;
    }
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHousing()) {
      hash = (37 * hash) + HOUSING_FIELD_NUMBER;
      hash = (53 * hash) + getHousing().hashCode();
    }
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.group11.tier2.protobuf.GAddHousingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GAddHousingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GAddHousingRequest)
      via.sep3.group11.tier2.protobuf.GAddHousingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.group11.tier2.protobuf.HousingOuterClass.internal_static_GAddHousingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.group11.tier2.protobuf.HousingOuterClass.internal_static_GAddHousingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.group11.tier2.protobuf.GAddHousingRequest.class, via.sep3.group11.tier2.protobuf.GAddHousingRequest.Builder.class);
    }

    // Construct using via.sep3.group11.tier2.protobuf.GAddHousingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (housingBuilder_ == null) {
        housing_ = null;
      } else {
        housing_ = null;
        housingBuilder_ = null;
      }
      email_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.group11.tier2.protobuf.HousingOuterClass.internal_static_GAddHousingRequest_descriptor;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GAddHousingRequest getDefaultInstanceForType() {
      return via.sep3.group11.tier2.protobuf.GAddHousingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GAddHousingRequest build() {
      via.sep3.group11.tier2.protobuf.GAddHousingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GAddHousingRequest buildPartial() {
      via.sep3.group11.tier2.protobuf.GAddHousingRequest result = new via.sep3.group11.tier2.protobuf.GAddHousingRequest(this);
      if (housingBuilder_ == null) {
        result.housing_ = housing_;
      } else {
        result.housing_ = housingBuilder_.build();
      }
      result.email_ = email_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.group11.tier2.protobuf.GAddHousingRequest) {
        return mergeFrom((via.sep3.group11.tier2.protobuf.GAddHousingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.group11.tier2.protobuf.GAddHousingRequest other) {
      if (other == via.sep3.group11.tier2.protobuf.GAddHousingRequest.getDefaultInstance()) return this;
      if (other.hasHousing()) {
        mergeHousing(other.getHousing());
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.group11.tier2.protobuf.GAddHousingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.group11.tier2.protobuf.GAddHousingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private via.sep3.group11.tier2.protobuf.GHousing housing_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GHousing, via.sep3.group11.tier2.protobuf.GHousing.Builder, via.sep3.group11.tier2.protobuf.GHousingOrBuilder> housingBuilder_;
    /**
     * <code>.GHousing housing = 1;</code>
     * @return Whether the housing field is set.
     */
    public boolean hasHousing() {
      return housingBuilder_ != null || housing_ != null;
    }
    /**
     * <code>.GHousing housing = 1;</code>
     * @return The housing.
     */
    public via.sep3.group11.tier2.protobuf.GHousing getHousing() {
      if (housingBuilder_ == null) {
        return housing_ == null ? via.sep3.group11.tier2.protobuf.GHousing.getDefaultInstance() : housing_;
      } else {
        return housingBuilder_.getMessage();
      }
    }
    /**
     * <code>.GHousing housing = 1;</code>
     */
    public Builder setHousing(via.sep3.group11.tier2.protobuf.GHousing value) {
      if (housingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        housing_ = value;
        onChanged();
      } else {
        housingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.GHousing housing = 1;</code>
     */
    public Builder setHousing(
        via.sep3.group11.tier2.protobuf.GHousing.Builder builderForValue) {
      if (housingBuilder_ == null) {
        housing_ = builderForValue.build();
        onChanged();
      } else {
        housingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.GHousing housing = 1;</code>
     */
    public Builder mergeHousing(via.sep3.group11.tier2.protobuf.GHousing value) {
      if (housingBuilder_ == null) {
        if (housing_ != null) {
          housing_ =
            via.sep3.group11.tier2.protobuf.GHousing.newBuilder(housing_).mergeFrom(value).buildPartial();
        } else {
          housing_ = value;
        }
        onChanged();
      } else {
        housingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.GHousing housing = 1;</code>
     */
    public Builder clearHousing() {
      if (housingBuilder_ == null) {
        housing_ = null;
        onChanged();
      } else {
        housing_ = null;
        housingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.GHousing housing = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GHousing.Builder getHousingBuilder() {
      
      onChanged();
      return getHousingFieldBuilder().getBuilder();
    }
    /**
     * <code>.GHousing housing = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GHousingOrBuilder getHousingOrBuilder() {
      if (housingBuilder_ != null) {
        return housingBuilder_.getMessageOrBuilder();
      } else {
        return housing_ == null ?
            via.sep3.group11.tier2.protobuf.GHousing.getDefaultInstance() : housing_;
      }
    }
    /**
     * <code>.GHousing housing = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GHousing, via.sep3.group11.tier2.protobuf.GHousing.Builder, via.sep3.group11.tier2.protobuf.GHousingOrBuilder> 
        getHousingFieldBuilder() {
      if (housingBuilder_ == null) {
        housingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.group11.tier2.protobuf.GHousing, via.sep3.group11.tier2.protobuf.GHousing.Builder, via.sep3.group11.tier2.protobuf.GHousingOrBuilder>(
                getHousing(),
                getParentForChildren(),
                isClean());
        housing_ = null;
      }
      return housingBuilder_;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 2;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 2;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 2;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 2;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GAddHousingRequest)
  }

  // @@protoc_insertion_point(class_scope:GAddHousingRequest)
  private static final via.sep3.group11.tier2.protobuf.GAddHousingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.group11.tier2.protobuf.GAddHousingRequest();
  }

  public static via.sep3.group11.tier2.protobuf.GAddHousingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GAddHousingRequest>
      PARSER = new com.google.protobuf.AbstractParser<GAddHousingRequest>() {
    @java.lang.Override
    public GAddHousingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GAddHousingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GAddHousingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GAddHousingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GAddHousingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

