// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Agreement.proto

package via.sep3.group11.tier2.protobuf;

public interface GAgreementListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GAgreementList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GAgreement agreements = 1;</code>
   */
  java.util.List<via.sep3.group11.tier2.protobuf.GAgreement> 
      getAgreementsList();
  /**
   * <code>repeated .GAgreement agreements = 1;</code>
   */
  via.sep3.group11.tier2.protobuf.GAgreement getAgreements(int index);
  /**
   * <code>repeated .GAgreement agreements = 1;</code>
   */
  int getAgreementsCount();
  /**
   * <code>repeated .GAgreement agreements = 1;</code>
   */
  java.util.List<? extends via.sep3.group11.tier2.protobuf.GAgreementOrBuilder> 
      getAgreementsOrBuilderList();
  /**
   * <code>repeated .GAgreement agreements = 1;</code>
   */
  via.sep3.group11.tier2.protobuf.GAgreementOrBuilder getAgreementsOrBuilder(
      int index);
}
