// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SharedMessages.proto

package via.sep3.group11.tier2.protobuf;

/**
 * Protobuf type {@code GAgreement}
 */
public final class GAgreement extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GAgreement)
    GAgreementOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GAgreement.newBuilder() to construct.
  private GAgreement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GAgreement() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GAgreement();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GAgreement(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder subBuilder = null;
            if (dateOfCreation_ != null) {
              subBuilder = dateOfCreation_.toBuilder();
            }
            dateOfCreation_ = input.readMessage(via.sep3.group11.tier2.protobuf.GDateOfBirth.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateOfCreation_);
              dateOfCreation_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            via.sep3.group11.tier2.protobuf.GHostDetails.Builder subBuilder = null;
            if (hostDetails_ != null) {
              subBuilder = hostDetails_.toBuilder();
            }
            hostDetails_ = input.readMessage(via.sep3.group11.tier2.protobuf.GHostDetails.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(hostDetails_);
              hostDetails_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder subBuilder = null;
            if (housing_ != null) {
              subBuilder = housing_.toBuilder();
            }
            housing_ = input.readMessage(via.sep3.group11.tier2.protobuf.GHousingWithStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(housing_);
              housing_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            via.sep3.group11.tier2.protobuf.GRefugee.Builder subBuilder = null;
            if (refugee_ != null) {
              subBuilder = refugee_.toBuilder();
            }
            refugee_ = input.readMessage(via.sep3.group11.tier2.protobuf.GRefugee.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(refugee_);
              refugee_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            status_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GAgreement_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GAgreement_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.group11.tier2.protobuf.GAgreement.class, via.sep3.group11.tier2.protobuf.GAgreement.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int DATEOFCREATION_FIELD_NUMBER = 2;
  private via.sep3.group11.tier2.protobuf.GDateOfBirth dateOfCreation_;
  /**
   * <code>.GDateOfBirth dateOfCreation = 2;</code>
   * @return Whether the dateOfCreation field is set.
   */
  @java.lang.Override
  public boolean hasDateOfCreation() {
    return dateOfCreation_ != null;
  }
  /**
   * <code>.GDateOfBirth dateOfCreation = 2;</code>
   * @return The dateOfCreation.
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GDateOfBirth getDateOfCreation() {
    return dateOfCreation_ == null ? via.sep3.group11.tier2.protobuf.GDateOfBirth.getDefaultInstance() : dateOfCreation_;
  }
  /**
   * <code>.GDateOfBirth dateOfCreation = 2;</code>
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GDateOfBirthOrBuilder getDateOfCreationOrBuilder() {
    return getDateOfCreation();
  }

  public static final int HOSTDETAILS_FIELD_NUMBER = 3;
  private via.sep3.group11.tier2.protobuf.GHostDetails hostDetails_;
  /**
   * <code>.GHostDetails hostDetails = 3;</code>
   * @return Whether the hostDetails field is set.
   */
  @java.lang.Override
  public boolean hasHostDetails() {
    return hostDetails_ != null;
  }
  /**
   * <code>.GHostDetails hostDetails = 3;</code>
   * @return The hostDetails.
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GHostDetails getHostDetails() {
    return hostDetails_ == null ? via.sep3.group11.tier2.protobuf.GHostDetails.getDefaultInstance() : hostDetails_;
  }
  /**
   * <code>.GHostDetails hostDetails = 3;</code>
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GHostDetailsOrBuilder getHostDetailsOrBuilder() {
    return getHostDetails();
  }

  public static final int HOUSING_FIELD_NUMBER = 4;
  private via.sep3.group11.tier2.protobuf.GHousingWithStatus housing_;
  /**
   * <code>.GHousingWithStatus housing = 4;</code>
   * @return Whether the housing field is set.
   */
  @java.lang.Override
  public boolean hasHousing() {
    return housing_ != null;
  }
  /**
   * <code>.GHousingWithStatus housing = 4;</code>
   * @return The housing.
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GHousingWithStatus getHousing() {
    return housing_ == null ? via.sep3.group11.tier2.protobuf.GHousingWithStatus.getDefaultInstance() : housing_;
  }
  /**
   * <code>.GHousingWithStatus housing = 4;</code>
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder getHousingOrBuilder() {
    return getHousing();
  }

  public static final int REFUGEE_FIELD_NUMBER = 5;
  private via.sep3.group11.tier2.protobuf.GRefugee refugee_;
  /**
   * <code>.GRefugee refugee = 5;</code>
   * @return Whether the refugee field is set.
   */
  @java.lang.Override
  public boolean hasRefugee() {
    return refugee_ != null;
  }
  /**
   * <code>.GRefugee refugee = 5;</code>
   * @return The refugee.
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GRefugee getRefugee() {
    return refugee_ == null ? via.sep3.group11.tier2.protobuf.GRefugee.getDefaultInstance() : refugee_;
  }
  /**
   * <code>.GRefugee refugee = 5;</code>
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GRefugeeOrBuilder getRefugeeOrBuilder() {
    return getRefugee();
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private boolean status_;
  /**
   * <code>bool status = 6;</code>
   * @return The status.
   */
  @java.lang.Override
  public boolean getStatus() {
    return status_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (dateOfCreation_ != null) {
      output.writeMessage(2, getDateOfCreation());
    }
    if (hostDetails_ != null) {
      output.writeMessage(3, getHostDetails());
    }
    if (housing_ != null) {
      output.writeMessage(4, getHousing());
    }
    if (refugee_ != null) {
      output.writeMessage(5, getRefugee());
    }
    if (status_ != false) {
      output.writeBool(6, status_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (dateOfCreation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDateOfCreation());
    }
    if (hostDetails_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getHostDetails());
    }
    if (housing_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getHousing());
    }
    if (refugee_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getRefugee());
    }
    if (status_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.group11.tier2.protobuf.GAgreement)) {
      return super.equals(obj);
    }
    via.sep3.group11.tier2.protobuf.GAgreement other = (via.sep3.group11.tier2.protobuf.GAgreement) obj;

    if (getId()
        != other.getId()) return false;
    if (hasDateOfCreation() != other.hasDateOfCreation()) return false;
    if (hasDateOfCreation()) {
      if (!getDateOfCreation()
          .equals(other.getDateOfCreation())) return false;
    }
    if (hasHostDetails() != other.hasHostDetails()) return false;
    if (hasHostDetails()) {
      if (!getHostDetails()
          .equals(other.getHostDetails())) return false;
    }
    if (hasHousing() != other.hasHousing()) return false;
    if (hasHousing()) {
      if (!getHousing()
          .equals(other.getHousing())) return false;
    }
    if (hasRefugee() != other.hasRefugee()) return false;
    if (hasRefugee()) {
      if (!getRefugee()
          .equals(other.getRefugee())) return false;
    }
    if (getStatus()
        != other.getStatus()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasDateOfCreation()) {
      hash = (37 * hash) + DATEOFCREATION_FIELD_NUMBER;
      hash = (53 * hash) + getDateOfCreation().hashCode();
    }
    if (hasHostDetails()) {
      hash = (37 * hash) + HOSTDETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getHostDetails().hashCode();
    }
    if (hasHousing()) {
      hash = (37 * hash) + HOUSING_FIELD_NUMBER;
      hash = (53 * hash) + getHousing().hashCode();
    }
    if (hasRefugee()) {
      hash = (37 * hash) + REFUGEE_FIELD_NUMBER;
      hash = (53 * hash) + getRefugee().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStatus());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.group11.tier2.protobuf.GAgreement parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GAgreement parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAgreement parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GAgreement parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAgreement parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GAgreement parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAgreement parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GAgreement parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAgreement parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GAgreement parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAgreement parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GAgreement parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.group11.tier2.protobuf.GAgreement prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GAgreement}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GAgreement)
      via.sep3.group11.tier2.protobuf.GAgreementOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GAgreement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GAgreement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.group11.tier2.protobuf.GAgreement.class, via.sep3.group11.tier2.protobuf.GAgreement.Builder.class);
    }

    // Construct using via.sep3.group11.tier2.protobuf.GAgreement.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      if (dateOfCreationBuilder_ == null) {
        dateOfCreation_ = null;
      } else {
        dateOfCreation_ = null;
        dateOfCreationBuilder_ = null;
      }
      if (hostDetailsBuilder_ == null) {
        hostDetails_ = null;
      } else {
        hostDetails_ = null;
        hostDetailsBuilder_ = null;
      }
      if (housingBuilder_ == null) {
        housing_ = null;
      } else {
        housing_ = null;
        housingBuilder_ = null;
      }
      if (refugeeBuilder_ == null) {
        refugee_ = null;
      } else {
        refugee_ = null;
        refugeeBuilder_ = null;
      }
      status_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GAgreement_descriptor;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GAgreement getDefaultInstanceForType() {
      return via.sep3.group11.tier2.protobuf.GAgreement.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GAgreement build() {
      via.sep3.group11.tier2.protobuf.GAgreement result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GAgreement buildPartial() {
      via.sep3.group11.tier2.protobuf.GAgreement result = new via.sep3.group11.tier2.protobuf.GAgreement(this);
      result.id_ = id_;
      if (dateOfCreationBuilder_ == null) {
        result.dateOfCreation_ = dateOfCreation_;
      } else {
        result.dateOfCreation_ = dateOfCreationBuilder_.build();
      }
      if (hostDetailsBuilder_ == null) {
        result.hostDetails_ = hostDetails_;
      } else {
        result.hostDetails_ = hostDetailsBuilder_.build();
      }
      if (housingBuilder_ == null) {
        result.housing_ = housing_;
      } else {
        result.housing_ = housingBuilder_.build();
      }
      if (refugeeBuilder_ == null) {
        result.refugee_ = refugee_;
      } else {
        result.refugee_ = refugeeBuilder_.build();
      }
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.group11.tier2.protobuf.GAgreement) {
        return mergeFrom((via.sep3.group11.tier2.protobuf.GAgreement)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.group11.tier2.protobuf.GAgreement other) {
      if (other == via.sep3.group11.tier2.protobuf.GAgreement.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasDateOfCreation()) {
        mergeDateOfCreation(other.getDateOfCreation());
      }
      if (other.hasHostDetails()) {
        mergeHostDetails(other.getHostDetails());
      }
      if (other.hasHousing()) {
        mergeHousing(other.getHousing());
      }
      if (other.hasRefugee()) {
        mergeRefugee(other.getRefugee());
      }
      if (other.getStatus() != false) {
        setStatus(other.getStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.group11.tier2.protobuf.GAgreement parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.group11.tier2.protobuf.GAgreement) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private via.sep3.group11.tier2.protobuf.GDateOfBirth dateOfCreation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GDateOfBirth, via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder, via.sep3.group11.tier2.protobuf.GDateOfBirthOrBuilder> dateOfCreationBuilder_;
    /**
     * <code>.GDateOfBirth dateOfCreation = 2;</code>
     * @return Whether the dateOfCreation field is set.
     */
    public boolean hasDateOfCreation() {
      return dateOfCreationBuilder_ != null || dateOfCreation_ != null;
    }
    /**
     * <code>.GDateOfBirth dateOfCreation = 2;</code>
     * @return The dateOfCreation.
     */
    public via.sep3.group11.tier2.protobuf.GDateOfBirth getDateOfCreation() {
      if (dateOfCreationBuilder_ == null) {
        return dateOfCreation_ == null ? via.sep3.group11.tier2.protobuf.GDateOfBirth.getDefaultInstance() : dateOfCreation_;
      } else {
        return dateOfCreationBuilder_.getMessage();
      }
    }
    /**
     * <code>.GDateOfBirth dateOfCreation = 2;</code>
     */
    public Builder setDateOfCreation(via.sep3.group11.tier2.protobuf.GDateOfBirth value) {
      if (dateOfCreationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateOfCreation_ = value;
        onChanged();
      } else {
        dateOfCreationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.GDateOfBirth dateOfCreation = 2;</code>
     */
    public Builder setDateOfCreation(
        via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder builderForValue) {
      if (dateOfCreationBuilder_ == null) {
        dateOfCreation_ = builderForValue.build();
        onChanged();
      } else {
        dateOfCreationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.GDateOfBirth dateOfCreation = 2;</code>
     */
    public Builder mergeDateOfCreation(via.sep3.group11.tier2.protobuf.GDateOfBirth value) {
      if (dateOfCreationBuilder_ == null) {
        if (dateOfCreation_ != null) {
          dateOfCreation_ =
            via.sep3.group11.tier2.protobuf.GDateOfBirth.newBuilder(dateOfCreation_).mergeFrom(value).buildPartial();
        } else {
          dateOfCreation_ = value;
        }
        onChanged();
      } else {
        dateOfCreationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.GDateOfBirth dateOfCreation = 2;</code>
     */
    public Builder clearDateOfCreation() {
      if (dateOfCreationBuilder_ == null) {
        dateOfCreation_ = null;
        onChanged();
      } else {
        dateOfCreation_ = null;
        dateOfCreationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.GDateOfBirth dateOfCreation = 2;</code>
     */
    public via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder getDateOfCreationBuilder() {
      
      onChanged();
      return getDateOfCreationFieldBuilder().getBuilder();
    }
    /**
     * <code>.GDateOfBirth dateOfCreation = 2;</code>
     */
    public via.sep3.group11.tier2.protobuf.GDateOfBirthOrBuilder getDateOfCreationOrBuilder() {
      if (dateOfCreationBuilder_ != null) {
        return dateOfCreationBuilder_.getMessageOrBuilder();
      } else {
        return dateOfCreation_ == null ?
            via.sep3.group11.tier2.protobuf.GDateOfBirth.getDefaultInstance() : dateOfCreation_;
      }
    }
    /**
     * <code>.GDateOfBirth dateOfCreation = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GDateOfBirth, via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder, via.sep3.group11.tier2.protobuf.GDateOfBirthOrBuilder> 
        getDateOfCreationFieldBuilder() {
      if (dateOfCreationBuilder_ == null) {
        dateOfCreationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.group11.tier2.protobuf.GDateOfBirth, via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder, via.sep3.group11.tier2.protobuf.GDateOfBirthOrBuilder>(
                getDateOfCreation(),
                getParentForChildren(),
                isClean());
        dateOfCreation_ = null;
      }
      return dateOfCreationBuilder_;
    }

    private via.sep3.group11.tier2.protobuf.GHostDetails hostDetails_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GHostDetails, via.sep3.group11.tier2.protobuf.GHostDetails.Builder, via.sep3.group11.tier2.protobuf.GHostDetailsOrBuilder> hostDetailsBuilder_;
    /**
     * <code>.GHostDetails hostDetails = 3;</code>
     * @return Whether the hostDetails field is set.
     */
    public boolean hasHostDetails() {
      return hostDetailsBuilder_ != null || hostDetails_ != null;
    }
    /**
     * <code>.GHostDetails hostDetails = 3;</code>
     * @return The hostDetails.
     */
    public via.sep3.group11.tier2.protobuf.GHostDetails getHostDetails() {
      if (hostDetailsBuilder_ == null) {
        return hostDetails_ == null ? via.sep3.group11.tier2.protobuf.GHostDetails.getDefaultInstance() : hostDetails_;
      } else {
        return hostDetailsBuilder_.getMessage();
      }
    }
    /**
     * <code>.GHostDetails hostDetails = 3;</code>
     */
    public Builder setHostDetails(via.sep3.group11.tier2.protobuf.GHostDetails value) {
      if (hostDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hostDetails_ = value;
        onChanged();
      } else {
        hostDetailsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.GHostDetails hostDetails = 3;</code>
     */
    public Builder setHostDetails(
        via.sep3.group11.tier2.protobuf.GHostDetails.Builder builderForValue) {
      if (hostDetailsBuilder_ == null) {
        hostDetails_ = builderForValue.build();
        onChanged();
      } else {
        hostDetailsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.GHostDetails hostDetails = 3;</code>
     */
    public Builder mergeHostDetails(via.sep3.group11.tier2.protobuf.GHostDetails value) {
      if (hostDetailsBuilder_ == null) {
        if (hostDetails_ != null) {
          hostDetails_ =
            via.sep3.group11.tier2.protobuf.GHostDetails.newBuilder(hostDetails_).mergeFrom(value).buildPartial();
        } else {
          hostDetails_ = value;
        }
        onChanged();
      } else {
        hostDetailsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.GHostDetails hostDetails = 3;</code>
     */
    public Builder clearHostDetails() {
      if (hostDetailsBuilder_ == null) {
        hostDetails_ = null;
        onChanged();
      } else {
        hostDetails_ = null;
        hostDetailsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.GHostDetails hostDetails = 3;</code>
     */
    public via.sep3.group11.tier2.protobuf.GHostDetails.Builder getHostDetailsBuilder() {
      
      onChanged();
      return getHostDetailsFieldBuilder().getBuilder();
    }
    /**
     * <code>.GHostDetails hostDetails = 3;</code>
     */
    public via.sep3.group11.tier2.protobuf.GHostDetailsOrBuilder getHostDetailsOrBuilder() {
      if (hostDetailsBuilder_ != null) {
        return hostDetailsBuilder_.getMessageOrBuilder();
      } else {
        return hostDetails_ == null ?
            via.sep3.group11.tier2.protobuf.GHostDetails.getDefaultInstance() : hostDetails_;
      }
    }
    /**
     * <code>.GHostDetails hostDetails = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GHostDetails, via.sep3.group11.tier2.protobuf.GHostDetails.Builder, via.sep3.group11.tier2.protobuf.GHostDetailsOrBuilder> 
        getHostDetailsFieldBuilder() {
      if (hostDetailsBuilder_ == null) {
        hostDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.group11.tier2.protobuf.GHostDetails, via.sep3.group11.tier2.protobuf.GHostDetails.Builder, via.sep3.group11.tier2.protobuf.GHostDetailsOrBuilder>(
                getHostDetails(),
                getParentForChildren(),
                isClean());
        hostDetails_ = null;
      }
      return hostDetailsBuilder_;
    }

    private via.sep3.group11.tier2.protobuf.GHousingWithStatus housing_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GHousingWithStatus, via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder, via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder> housingBuilder_;
    /**
     * <code>.GHousingWithStatus housing = 4;</code>
     * @return Whether the housing field is set.
     */
    public boolean hasHousing() {
      return housingBuilder_ != null || housing_ != null;
    }
    /**
     * <code>.GHousingWithStatus housing = 4;</code>
     * @return The housing.
     */
    public via.sep3.group11.tier2.protobuf.GHousingWithStatus getHousing() {
      if (housingBuilder_ == null) {
        return housing_ == null ? via.sep3.group11.tier2.protobuf.GHousingWithStatus.getDefaultInstance() : housing_;
      } else {
        return housingBuilder_.getMessage();
      }
    }
    /**
     * <code>.GHousingWithStatus housing = 4;</code>
     */
    public Builder setHousing(via.sep3.group11.tier2.protobuf.GHousingWithStatus value) {
      if (housingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        housing_ = value;
        onChanged();
      } else {
        housingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.GHousingWithStatus housing = 4;</code>
     */
    public Builder setHousing(
        via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder builderForValue) {
      if (housingBuilder_ == null) {
        housing_ = builderForValue.build();
        onChanged();
      } else {
        housingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.GHousingWithStatus housing = 4;</code>
     */
    public Builder mergeHousing(via.sep3.group11.tier2.protobuf.GHousingWithStatus value) {
      if (housingBuilder_ == null) {
        if (housing_ != null) {
          housing_ =
            via.sep3.group11.tier2.protobuf.GHousingWithStatus.newBuilder(housing_).mergeFrom(value).buildPartial();
        } else {
          housing_ = value;
        }
        onChanged();
      } else {
        housingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.GHousingWithStatus housing = 4;</code>
     */
    public Builder clearHousing() {
      if (housingBuilder_ == null) {
        housing_ = null;
        onChanged();
      } else {
        housing_ = null;
        housingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.GHousingWithStatus housing = 4;</code>
     */
    public via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder getHousingBuilder() {
      
      onChanged();
      return getHousingFieldBuilder().getBuilder();
    }
    /**
     * <code>.GHousingWithStatus housing = 4;</code>
     */
    public via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder getHousingOrBuilder() {
      if (housingBuilder_ != null) {
        return housingBuilder_.getMessageOrBuilder();
      } else {
        return housing_ == null ?
            via.sep3.group11.tier2.protobuf.GHousingWithStatus.getDefaultInstance() : housing_;
      }
    }
    /**
     * <code>.GHousingWithStatus housing = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GHousingWithStatus, via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder, via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder> 
        getHousingFieldBuilder() {
      if (housingBuilder_ == null) {
        housingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.group11.tier2.protobuf.GHousingWithStatus, via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder, via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder>(
                getHousing(),
                getParentForChildren(),
                isClean());
        housing_ = null;
      }
      return housingBuilder_;
    }

    private via.sep3.group11.tier2.protobuf.GRefugee refugee_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GRefugee, via.sep3.group11.tier2.protobuf.GRefugee.Builder, via.sep3.group11.tier2.protobuf.GRefugeeOrBuilder> refugeeBuilder_;
    /**
     * <code>.GRefugee refugee = 5;</code>
     * @return Whether the refugee field is set.
     */
    public boolean hasRefugee() {
      return refugeeBuilder_ != null || refugee_ != null;
    }
    /**
     * <code>.GRefugee refugee = 5;</code>
     * @return The refugee.
     */
    public via.sep3.group11.tier2.protobuf.GRefugee getRefugee() {
      if (refugeeBuilder_ == null) {
        return refugee_ == null ? via.sep3.group11.tier2.protobuf.GRefugee.getDefaultInstance() : refugee_;
      } else {
        return refugeeBuilder_.getMessage();
      }
    }
    /**
     * <code>.GRefugee refugee = 5;</code>
     */
    public Builder setRefugee(via.sep3.group11.tier2.protobuf.GRefugee value) {
      if (refugeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        refugee_ = value;
        onChanged();
      } else {
        refugeeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.GRefugee refugee = 5;</code>
     */
    public Builder setRefugee(
        via.sep3.group11.tier2.protobuf.GRefugee.Builder builderForValue) {
      if (refugeeBuilder_ == null) {
        refugee_ = builderForValue.build();
        onChanged();
      } else {
        refugeeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.GRefugee refugee = 5;</code>
     */
    public Builder mergeRefugee(via.sep3.group11.tier2.protobuf.GRefugee value) {
      if (refugeeBuilder_ == null) {
        if (refugee_ != null) {
          refugee_ =
            via.sep3.group11.tier2.protobuf.GRefugee.newBuilder(refugee_).mergeFrom(value).buildPartial();
        } else {
          refugee_ = value;
        }
        onChanged();
      } else {
        refugeeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.GRefugee refugee = 5;</code>
     */
    public Builder clearRefugee() {
      if (refugeeBuilder_ == null) {
        refugee_ = null;
        onChanged();
      } else {
        refugee_ = null;
        refugeeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.GRefugee refugee = 5;</code>
     */
    public via.sep3.group11.tier2.protobuf.GRefugee.Builder getRefugeeBuilder() {
      
      onChanged();
      return getRefugeeFieldBuilder().getBuilder();
    }
    /**
     * <code>.GRefugee refugee = 5;</code>
     */
    public via.sep3.group11.tier2.protobuf.GRefugeeOrBuilder getRefugeeOrBuilder() {
      if (refugeeBuilder_ != null) {
        return refugeeBuilder_.getMessageOrBuilder();
      } else {
        return refugee_ == null ?
            via.sep3.group11.tier2.protobuf.GRefugee.getDefaultInstance() : refugee_;
      }
    }
    /**
     * <code>.GRefugee refugee = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GRefugee, via.sep3.group11.tier2.protobuf.GRefugee.Builder, via.sep3.group11.tier2.protobuf.GRefugeeOrBuilder> 
        getRefugeeFieldBuilder() {
      if (refugeeBuilder_ == null) {
        refugeeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.group11.tier2.protobuf.GRefugee, via.sep3.group11.tier2.protobuf.GRefugee.Builder, via.sep3.group11.tier2.protobuf.GRefugeeOrBuilder>(
                getRefugee(),
                getParentForChildren(),
                isClean());
        refugee_ = null;
      }
      return refugeeBuilder_;
    }

    private boolean status_ ;
    /**
     * <code>bool status = 6;</code>
     * @return The status.
     */
    @java.lang.Override
    public boolean getStatus() {
      return status_;
    }
    /**
     * <code>bool status = 6;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(boolean value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GAgreement)
  }

  // @@protoc_insertion_point(class_scope:GAgreement)
  private static final via.sep3.group11.tier2.protobuf.GAgreement DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.group11.tier2.protobuf.GAgreement();
  }

  public static via.sep3.group11.tier2.protobuf.GAgreement getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GAgreement>
      PARSER = new com.google.protobuf.AbstractParser<GAgreement>() {
    @java.lang.Override
    public GAgreement parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GAgreement(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GAgreement> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GAgreement> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GAgreement getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

