// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Agreement.proto

package via.sep3.group11.tier2.protobuf;

/**
 * Protobuf type {@code getAllPendingAgreementsResponse}
 */
public final class getAllPendingAgreementsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:getAllPendingAgreementsResponse)
    getAllPendingAgreementsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use getAllPendingAgreementsResponse.newBuilder() to construct.
  private getAllPendingAgreementsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private getAllPendingAgreementsResponse() {
    agreements_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new getAllPendingAgreementsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private getAllPendingAgreementsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              agreements_ = new java.util.ArrayList<via.sep3.group11.tier2.protobuf.GAgreement>();
              mutable_bitField0_ |= 0x00000001;
            }
            agreements_.add(
                input.readMessage(via.sep3.group11.tier2.protobuf.GAgreement.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        agreements_ = java.util.Collections.unmodifiableList(agreements_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.group11.tier2.protobuf.AgreementOuterClass.internal_static_getAllPendingAgreementsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.group11.tier2.protobuf.AgreementOuterClass.internal_static_getAllPendingAgreementsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse.class, via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse.Builder.class);
  }

  public static final int AGREEMENTS_FIELD_NUMBER = 1;
  private java.util.List<via.sep3.group11.tier2.protobuf.GAgreement> agreements_;
  /**
   * <code>repeated .GAgreement agreements = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sep3.group11.tier2.protobuf.GAgreement> getAgreementsList() {
    return agreements_;
  }
  /**
   * <code>repeated .GAgreement agreements = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sep3.group11.tier2.protobuf.GAgreementOrBuilder> 
      getAgreementsOrBuilderList() {
    return agreements_;
  }
  /**
   * <code>repeated .GAgreement agreements = 1;</code>
   */
  @java.lang.Override
  public int getAgreementsCount() {
    return agreements_.size();
  }
  /**
   * <code>repeated .GAgreement agreements = 1;</code>
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GAgreement getAgreements(int index) {
    return agreements_.get(index);
  }
  /**
   * <code>repeated .GAgreement agreements = 1;</code>
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GAgreementOrBuilder getAgreementsOrBuilder(
      int index) {
    return agreements_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < agreements_.size(); i++) {
      output.writeMessage(1, agreements_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < agreements_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, agreements_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse)) {
      return super.equals(obj);
    }
    via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse other = (via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse) obj;

    if (!getAgreementsList()
        .equals(other.getAgreementsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAgreementsCount() > 0) {
      hash = (37 * hash) + AGREEMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getAgreementsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code getAllPendingAgreementsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:getAllPendingAgreementsResponse)
      via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.group11.tier2.protobuf.AgreementOuterClass.internal_static_getAllPendingAgreementsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.group11.tier2.protobuf.AgreementOuterClass.internal_static_getAllPendingAgreementsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse.class, via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse.Builder.class);
    }

    // Construct using via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAgreementsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (agreementsBuilder_ == null) {
        agreements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        agreementsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.group11.tier2.protobuf.AgreementOuterClass.internal_static_getAllPendingAgreementsResponse_descriptor;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse getDefaultInstanceForType() {
      return via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse build() {
      via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse buildPartial() {
      via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse result = new via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse(this);
      int from_bitField0_ = bitField0_;
      if (agreementsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          agreements_ = java.util.Collections.unmodifiableList(agreements_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.agreements_ = agreements_;
      } else {
        result.agreements_ = agreementsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse) {
        return mergeFrom((via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse other) {
      if (other == via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse.getDefaultInstance()) return this;
      if (agreementsBuilder_ == null) {
        if (!other.agreements_.isEmpty()) {
          if (agreements_.isEmpty()) {
            agreements_ = other.agreements_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAgreementsIsMutable();
            agreements_.addAll(other.agreements_);
          }
          onChanged();
        }
      } else {
        if (!other.agreements_.isEmpty()) {
          if (agreementsBuilder_.isEmpty()) {
            agreementsBuilder_.dispose();
            agreementsBuilder_ = null;
            agreements_ = other.agreements_;
            bitField0_ = (bitField0_ & ~0x00000001);
            agreementsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAgreementsFieldBuilder() : null;
          } else {
            agreementsBuilder_.addAllMessages(other.agreements_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sep3.group11.tier2.protobuf.GAgreement> agreements_ =
      java.util.Collections.emptyList();
    private void ensureAgreementsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        agreements_ = new java.util.ArrayList<via.sep3.group11.tier2.protobuf.GAgreement>(agreements_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GAgreement, via.sep3.group11.tier2.protobuf.GAgreement.Builder, via.sep3.group11.tier2.protobuf.GAgreementOrBuilder> agreementsBuilder_;

    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public java.util.List<via.sep3.group11.tier2.protobuf.GAgreement> getAgreementsList() {
      if (agreementsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(agreements_);
      } else {
        return agreementsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public int getAgreementsCount() {
      if (agreementsBuilder_ == null) {
        return agreements_.size();
      } else {
        return agreementsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GAgreement getAgreements(int index) {
      if (agreementsBuilder_ == null) {
        return agreements_.get(index);
      } else {
        return agreementsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public Builder setAgreements(
        int index, via.sep3.group11.tier2.protobuf.GAgreement value) {
      if (agreementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAgreementsIsMutable();
        agreements_.set(index, value);
        onChanged();
      } else {
        agreementsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public Builder setAgreements(
        int index, via.sep3.group11.tier2.protobuf.GAgreement.Builder builderForValue) {
      if (agreementsBuilder_ == null) {
        ensureAgreementsIsMutable();
        agreements_.set(index, builderForValue.build());
        onChanged();
      } else {
        agreementsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public Builder addAgreements(via.sep3.group11.tier2.protobuf.GAgreement value) {
      if (agreementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAgreementsIsMutable();
        agreements_.add(value);
        onChanged();
      } else {
        agreementsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public Builder addAgreements(
        int index, via.sep3.group11.tier2.protobuf.GAgreement value) {
      if (agreementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAgreementsIsMutable();
        agreements_.add(index, value);
        onChanged();
      } else {
        agreementsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public Builder addAgreements(
        via.sep3.group11.tier2.protobuf.GAgreement.Builder builderForValue) {
      if (agreementsBuilder_ == null) {
        ensureAgreementsIsMutable();
        agreements_.add(builderForValue.build());
        onChanged();
      } else {
        agreementsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public Builder addAgreements(
        int index, via.sep3.group11.tier2.protobuf.GAgreement.Builder builderForValue) {
      if (agreementsBuilder_ == null) {
        ensureAgreementsIsMutable();
        agreements_.add(index, builderForValue.build());
        onChanged();
      } else {
        agreementsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public Builder addAllAgreements(
        java.lang.Iterable<? extends via.sep3.group11.tier2.protobuf.GAgreement> values) {
      if (agreementsBuilder_ == null) {
        ensureAgreementsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, agreements_);
        onChanged();
      } else {
        agreementsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public Builder clearAgreements() {
      if (agreementsBuilder_ == null) {
        agreements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        agreementsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public Builder removeAgreements(int index) {
      if (agreementsBuilder_ == null) {
        ensureAgreementsIsMutable();
        agreements_.remove(index);
        onChanged();
      } else {
        agreementsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GAgreement.Builder getAgreementsBuilder(
        int index) {
      return getAgreementsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GAgreementOrBuilder getAgreementsOrBuilder(
        int index) {
      if (agreementsBuilder_ == null) {
        return agreements_.get(index);  } else {
        return agreementsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public java.util.List<? extends via.sep3.group11.tier2.protobuf.GAgreementOrBuilder> 
         getAgreementsOrBuilderList() {
      if (agreementsBuilder_ != null) {
        return agreementsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(agreements_);
      }
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GAgreement.Builder addAgreementsBuilder() {
      return getAgreementsFieldBuilder().addBuilder(
          via.sep3.group11.tier2.protobuf.GAgreement.getDefaultInstance());
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GAgreement.Builder addAgreementsBuilder(
        int index) {
      return getAgreementsFieldBuilder().addBuilder(
          index, via.sep3.group11.tier2.protobuf.GAgreement.getDefaultInstance());
    }
    /**
     * <code>repeated .GAgreement agreements = 1;</code>
     */
    public java.util.List<via.sep3.group11.tier2.protobuf.GAgreement.Builder> 
         getAgreementsBuilderList() {
      return getAgreementsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GAgreement, via.sep3.group11.tier2.protobuf.GAgreement.Builder, via.sep3.group11.tier2.protobuf.GAgreementOrBuilder> 
        getAgreementsFieldBuilder() {
      if (agreementsBuilder_ == null) {
        agreementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sep3.group11.tier2.protobuf.GAgreement, via.sep3.group11.tier2.protobuf.GAgreement.Builder, via.sep3.group11.tier2.protobuf.GAgreementOrBuilder>(
                agreements_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        agreements_ = null;
      }
      return agreementsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:getAllPendingAgreementsResponse)
  }

  // @@protoc_insertion_point(class_scope:getAllPendingAgreementsResponse)
  private static final via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse();
  }

  public static via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<getAllPendingAgreementsResponse>
      PARSER = new com.google.protobuf.AbstractParser<getAllPendingAgreementsResponse>() {
    @java.lang.Override
    public getAllPendingAgreementsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new getAllPendingAgreementsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<getAllPendingAgreementsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<getAllPendingAgreementsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.getAllPendingAgreementsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

