// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SharedMessages.proto

package via.sep3.group11.tier2.protobuf;

public interface GHousingWithStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GHousingWithStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 capacity = 1;</code>
   * @return The capacity.
   */
  int getCapacity();

  /**
   * <code>.GAddress address = 2;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.GAddress address = 2;</code>
   * @return The address.
   */
  via.sep3.group11.tier2.protobuf.GAddress getAddress();
  /**
   * <code>.GAddress address = 2;</code>
   */
  via.sep3.group11.tier2.protobuf.GAddressOrBuilder getAddressOrBuilder();

  /**
   * <code>int64 id = 3;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>bool available = 4;</code>
   * @return The available.
   */
  boolean getAvailable();
}
