// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Host.proto

package via.sep3.group11.tier2.protobuf;

public final class HostOuterClass {
  private HostOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nHost.proto\032\024SharedMessages.proto2\272\001\n\004H" +
      "ost\022\034\n\nCreateHost\022\006.GHost\032\006.GHost\022!\n\016Get" +
      "HostByEmail\022\007.GEmail\032\006.GHost\022\"\n\022getHostB" +
      "yHousingId\022\004.GId\032\006.GHost\022!\n\rdeleteAccoun" +
      "t\022\007.GEmail\032\007.GEmpty\022*\n\021updateInformation" +
      "\022\r.GHostDetails\032\006.GHostB#\n\037via.sep3.grou" +
      "p11.tier2.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.sep3.group11.tier2.protobuf.SharedMessages.getDescriptor(),
        });
    via.sep3.group11.tier2.protobuf.SharedMessages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
