// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Housing.proto

package via.sep3.group11.tier2.protobuf;

public final class HousingOuterClass {
  private HousingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GAddHousingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GAddHousingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListOfAvailableHousing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListOfAvailableHousing_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rHousing.proto\032\024SharedMessages.proto\"?\n" +
      "\022GAddHousingRequest\022\032\n\007housing\030\001 \001(\0132\t.G" +
      "Housing\022\r\n\005email\030\002 \001(\t\"?\n\026ListOfAvailabl" +
      "eHousing\022%\n\010housings\030\001 \003(\0132\023.GHousingWit" +
      "hStatus2\200\002\n\007Housing\0226\n\naddHousing\022\023.GAdd" +
      "HousingRequest\032\023.GHousingWithStatus\0226\n\023g" +
      "etAvailableHousing\022\006.Empty\032\027.ListOfAvail" +
      "ableHousing\022\035\n\rremoveHousing\022\004.GId\032\006.Emp" +
      "ty\022+\n\016getHousingById\022\004.GId\032\023.GHousingWit" +
      "hStatus\0229\n\rupdateHousing\022\023.GHousingWithS" +
      "tatus\032\023.GHousingWithStatusB#\n\037via.sep3.g" +
      "roup11.tier2.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.sep3.group11.tier2.protobuf.SharedMessages.getDescriptor(),
        });
    internal_static_GAddHousingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GAddHousingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GAddHousingRequest_descriptor,
        new java.lang.String[] { "Housing", "Email", });
    internal_static_ListOfAvailableHousing_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ListOfAvailableHousing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListOfAvailableHousing_descriptor,
        new java.lang.String[] { "Housings", });
    via.sep3.group11.tier2.protobuf.SharedMessages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
