// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Refugee.proto

package via.sep3.group11.tier2.protobuf;

public final class RefugeeOuterClass {
  private RefugeeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRefugee.proto\032\024SharedMessages.proto2Y\n" +
      "\007Refugee\022%\n\rcreateRefugee\022\t.GRefugee\032\t.G" +
      "Refugee\022\'\n\021getRefugeeByEmail\022\007.GEmail\032\t." +
      "GRefugeeB#\n\037via.sep3.group11.tier2.proto" +
      "bufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.sep3.group11.tier2.protobuf.SharedMessages.getDescriptor(),
        });
    via.sep3.group11.tier2.protobuf.SharedMessages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
