// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SharedMessages.proto

package via.sep3.group11.tier2.protobuf;

/**
 * Protobuf type {@code GAddress}
 */
public final class GAddress extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GAddress)
    GAddressOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GAddress.newBuilder() to construct.
  private GAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GAddress() {
    country_ = "";
    city_ = "";
    streetName_ = "";
    houseNumber_ = "";
    roomNumber_ = "";
    postCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GAddress();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GAddress(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            country_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            streetName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            houseNumber_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            roomNumber_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            postCode_ = s;
            break;
          }
          case 56: {

            id_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GAddress_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GAddress_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.group11.tier2.protobuf.GAddress.class, via.sep3.group11.tier2.protobuf.GAddress.Builder.class);
  }

  public static final int COUNTRY_FIELD_NUMBER = 1;
  private volatile java.lang.Object country_;
  /**
   * <code>string country = 1;</code>
   * @return The country.
   */
  @java.lang.Override
  public java.lang.String getCountry() {
    java.lang.Object ref = country_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      country_ = s;
      return s;
    }
  }
  /**
   * <code>string country = 1;</code>
   * @return The bytes for country.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCountryBytes() {
    java.lang.Object ref = country_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      country_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITY_FIELD_NUMBER = 2;
  private volatile java.lang.Object city_;
  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  @java.lang.Override
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREETNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object streetName_;
  /**
   * <code>string streetName = 3;</code>
   * @return The streetName.
   */
  @java.lang.Override
  public java.lang.String getStreetName() {
    java.lang.Object ref = streetName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      streetName_ = s;
      return s;
    }
  }
  /**
   * <code>string streetName = 3;</code>
   * @return The bytes for streetName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStreetNameBytes() {
    java.lang.Object ref = streetName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      streetName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOUSENUMBER_FIELD_NUMBER = 4;
  private volatile java.lang.Object houseNumber_;
  /**
   * <code>string houseNumber = 4;</code>
   * @return The houseNumber.
   */
  @java.lang.Override
  public java.lang.String getHouseNumber() {
    java.lang.Object ref = houseNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      houseNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string houseNumber = 4;</code>
   * @return The bytes for houseNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHouseNumberBytes() {
    java.lang.Object ref = houseNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      houseNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOMNUMBER_FIELD_NUMBER = 5;
  private volatile java.lang.Object roomNumber_;
  /**
   * <code>string roomNumber = 5;</code>
   * @return The roomNumber.
   */
  @java.lang.Override
  public java.lang.String getRoomNumber() {
    java.lang.Object ref = roomNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string roomNumber = 5;</code>
   * @return The bytes for roomNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoomNumberBytes() {
    java.lang.Object ref = roomNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSTCODE_FIELD_NUMBER = 6;
  private volatile java.lang.Object postCode_;
  /**
   * <code>string postCode = 6;</code>
   * @return The postCode.
   */
  @java.lang.Override
  public java.lang.String getPostCode() {
    java.lang.Object ref = postCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      postCode_ = s;
      return s;
    }
  }
  /**
   * <code>string postCode = 6;</code>
   * @return The bytes for postCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPostCodeBytes() {
    java.lang.Object ref = postCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      postCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 7;
  private long id_;
  /**
   * <code>int64 id = 7;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(country_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, country_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streetName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, streetName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(houseNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, houseNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, roomNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(postCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, postCode_);
    }
    if (id_ != 0L) {
      output.writeInt64(7, id_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(country_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, country_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streetName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, streetName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(houseNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, houseNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, roomNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(postCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, postCode_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.group11.tier2.protobuf.GAddress)) {
      return super.equals(obj);
    }
    via.sep3.group11.tier2.protobuf.GAddress other = (via.sep3.group11.tier2.protobuf.GAddress) obj;

    if (!getCountry()
        .equals(other.getCountry())) return false;
    if (!getCity()
        .equals(other.getCity())) return false;
    if (!getStreetName()
        .equals(other.getStreetName())) return false;
    if (!getHouseNumber()
        .equals(other.getHouseNumber())) return false;
    if (!getRoomNumber()
        .equals(other.getRoomNumber())) return false;
    if (!getPostCode()
        .equals(other.getPostCode())) return false;
    if (getId()
        != other.getId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
    hash = (53 * hash) + getCountry().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + STREETNAME_FIELD_NUMBER;
    hash = (53 * hash) + getStreetName().hashCode();
    hash = (37 * hash) + HOUSENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getHouseNumber().hashCode();
    hash = (37 * hash) + ROOMNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getRoomNumber().hashCode();
    hash = (37 * hash) + POSTCODE_FIELD_NUMBER;
    hash = (53 * hash) + getPostCode().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.group11.tier2.protobuf.GAddress parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GAddress parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAddress parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GAddress parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAddress parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GAddress parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAddress parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GAddress parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAddress parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GAddress parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GAddress parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GAddress parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.group11.tier2.protobuf.GAddress prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GAddress}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GAddress)
      via.sep3.group11.tier2.protobuf.GAddressOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GAddress_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GAddress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.group11.tier2.protobuf.GAddress.class, via.sep3.group11.tier2.protobuf.GAddress.Builder.class);
    }

    // Construct using via.sep3.group11.tier2.protobuf.GAddress.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      country_ = "";

      city_ = "";

      streetName_ = "";

      houseNumber_ = "";

      roomNumber_ = "";

      postCode_ = "";

      id_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GAddress_descriptor;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GAddress getDefaultInstanceForType() {
      return via.sep3.group11.tier2.protobuf.GAddress.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GAddress build() {
      via.sep3.group11.tier2.protobuf.GAddress result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GAddress buildPartial() {
      via.sep3.group11.tier2.protobuf.GAddress result = new via.sep3.group11.tier2.protobuf.GAddress(this);
      result.country_ = country_;
      result.city_ = city_;
      result.streetName_ = streetName_;
      result.houseNumber_ = houseNumber_;
      result.roomNumber_ = roomNumber_;
      result.postCode_ = postCode_;
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.group11.tier2.protobuf.GAddress) {
        return mergeFrom((via.sep3.group11.tier2.protobuf.GAddress)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.group11.tier2.protobuf.GAddress other) {
      if (other == via.sep3.group11.tier2.protobuf.GAddress.getDefaultInstance()) return this;
      if (!other.getCountry().isEmpty()) {
        country_ = other.country_;
        onChanged();
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (!other.getStreetName().isEmpty()) {
        streetName_ = other.streetName_;
        onChanged();
      }
      if (!other.getHouseNumber().isEmpty()) {
        houseNumber_ = other.houseNumber_;
        onChanged();
      }
      if (!other.getRoomNumber().isEmpty()) {
        roomNumber_ = other.roomNumber_;
        onChanged();
      }
      if (!other.getPostCode().isEmpty()) {
        postCode_ = other.postCode_;
        onChanged();
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.group11.tier2.protobuf.GAddress parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.group11.tier2.protobuf.GAddress) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object country_ = "";
    /**
     * <code>string country = 1;</code>
     * @return The country.
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string country = 1;</code>
     * @return The bytes for country.
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string country = 1;</code>
     * @param value The country to set.
     * @return This builder for chaining.
     */
    public Builder setCountry(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      country_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string country = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountry() {
      
      country_ = getDefaultInstance().getCountry();
      onChanged();
      return this;
    }
    /**
     * <code>string country = 1;</code>
     * @param value The bytes for country to set.
     * @return This builder for chaining.
     */
    public Builder setCountryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      country_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object city_ = "";
    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string city = 2;</code>
     * @param value The city to set.
     * @return This builder for chaining.
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string city = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <code>string city = 2;</code>
     * @param value The bytes for city to set.
     * @return This builder for chaining.
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object streetName_ = "";
    /**
     * <code>string streetName = 3;</code>
     * @return The streetName.
     */
    public java.lang.String getStreetName() {
      java.lang.Object ref = streetName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streetName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string streetName = 3;</code>
     * @return The bytes for streetName.
     */
    public com.google.protobuf.ByteString
        getStreetNameBytes() {
      java.lang.Object ref = streetName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string streetName = 3;</code>
     * @param value The streetName to set.
     * @return This builder for chaining.
     */
    public Builder setStreetName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      streetName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string streetName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreetName() {
      
      streetName_ = getDefaultInstance().getStreetName();
      onChanged();
      return this;
    }
    /**
     * <code>string streetName = 3;</code>
     * @param value The bytes for streetName to set.
     * @return This builder for chaining.
     */
    public Builder setStreetNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      streetName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object houseNumber_ = "";
    /**
     * <code>string houseNumber = 4;</code>
     * @return The houseNumber.
     */
    public java.lang.String getHouseNumber() {
      java.lang.Object ref = houseNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        houseNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string houseNumber = 4;</code>
     * @return The bytes for houseNumber.
     */
    public com.google.protobuf.ByteString
        getHouseNumberBytes() {
      java.lang.Object ref = houseNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        houseNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string houseNumber = 4;</code>
     * @param value The houseNumber to set.
     * @return This builder for chaining.
     */
    public Builder setHouseNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      houseNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string houseNumber = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHouseNumber() {
      
      houseNumber_ = getDefaultInstance().getHouseNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string houseNumber = 4;</code>
     * @param value The bytes for houseNumber to set.
     * @return This builder for chaining.
     */
    public Builder setHouseNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      houseNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object roomNumber_ = "";
    /**
     * <code>string roomNumber = 5;</code>
     * @return The roomNumber.
     */
    public java.lang.String getRoomNumber() {
      java.lang.Object ref = roomNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string roomNumber = 5;</code>
     * @return The bytes for roomNumber.
     */
    public com.google.protobuf.ByteString
        getRoomNumberBytes() {
      java.lang.Object ref = roomNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string roomNumber = 5;</code>
     * @param value The roomNumber to set.
     * @return This builder for chaining.
     */
    public Builder setRoomNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string roomNumber = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomNumber() {
      
      roomNumber_ = getDefaultInstance().getRoomNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string roomNumber = 5;</code>
     * @param value The bytes for roomNumber to set.
     * @return This builder for chaining.
     */
    public Builder setRoomNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object postCode_ = "";
    /**
     * <code>string postCode = 6;</code>
     * @return The postCode.
     */
    public java.lang.String getPostCode() {
      java.lang.Object ref = postCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        postCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string postCode = 6;</code>
     * @return The bytes for postCode.
     */
    public com.google.protobuf.ByteString
        getPostCodeBytes() {
      java.lang.Object ref = postCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string postCode = 6;</code>
     * @param value The postCode to set.
     * @return This builder for chaining.
     */
    public Builder setPostCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      postCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string postCode = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPostCode() {
      
      postCode_ = getDefaultInstance().getPostCode();
      onChanged();
      return this;
    }
    /**
     * <code>string postCode = 6;</code>
     * @param value The bytes for postCode to set.
     * @return This builder for chaining.
     */
    public Builder setPostCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      postCode_ = value;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 7;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 7;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GAddress)
  }

  // @@protoc_insertion_point(class_scope:GAddress)
  private static final via.sep3.group11.tier2.protobuf.GAddress DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.group11.tier2.protobuf.GAddress();
  }

  public static via.sep3.group11.tier2.protobuf.GAddress getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GAddress>
      PARSER = new com.google.protobuf.AbstractParser<GAddress>() {
    @java.lang.Override
    public GAddress parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GAddress(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GAddress> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GAddress> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GAddress getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

