// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SharedMessages.proto

package via.sep3.group11.tier2.protobuf;

public interface GDateOfBirthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GDateOfBirth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 day = 1;</code>
   * @return The day.
   */
  int getDay();

  /**
   * <code>int32 month = 2;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>int32 year = 3;</code>
   * @return The year.
   */
  int getYear();
}
