// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SharedMessages.proto

package via.sep3.group11.tier2.protobuf;

/**
 * <pre>
 * -- HOST
 * </pre>
 *
 * Protobuf type {@code GHostDetails}
 */
public final class GHostDetails extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GHostDetails)
    GHostDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GHostDetails.newBuilder() to construct.
  private GHostDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GHostDetails() {
    firstName_ = "";
    email_ = "";
    password_ = "";
    gender_ = "";
    nationality_ = "";
    middleName_ = "";
    lastName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GHostDetails();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GHostDetails(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            firstName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            gender_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            nationality_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            middleName_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            lastName_ = s;
            break;
          }
          case 66: {
            via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder subBuilder = null;
            if (dateOfBirth_ != null) {
              subBuilder = dateOfBirth_.toBuilder();
            }
            dateOfBirth_ = input.readMessage(via.sep3.group11.tier2.protobuf.GDateOfBirth.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateOfBirth_);
              dateOfBirth_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GHostDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GHostDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.group11.tier2.protobuf.GHostDetails.class, via.sep3.group11.tier2.protobuf.GHostDetails.Builder.class);
  }

  public static final int FIRSTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object firstName_;
  /**
   * <code>string firstName = 1;</code>
   * @return The firstName.
   */
  @java.lang.Override
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <code>string firstName = 1;</code>
   * @return The bytes for firstName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 2;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object password_;
  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 4;
  private volatile java.lang.Object gender_;
  /**
   * <code>string gender = 4;</code>
   * @return The gender.
   */
  @java.lang.Override
  public java.lang.String getGender() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gender_ = s;
      return s;
    }
  }
  /**
   * <code>string gender = 4;</code>
   * @return The bytes for gender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenderBytes() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NATIONALITY_FIELD_NUMBER = 5;
  private volatile java.lang.Object nationality_;
  /**
   * <code>string nationality = 5;</code>
   * @return The nationality.
   */
  @java.lang.Override
  public java.lang.String getNationality() {
    java.lang.Object ref = nationality_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nationality_ = s;
      return s;
    }
  }
  /**
   * <code>string nationality = 5;</code>
   * @return The bytes for nationality.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNationalityBytes() {
    java.lang.Object ref = nationality_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nationality_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MIDDLENAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object middleName_;
  /**
   * <code>string middleName = 6;</code>
   * @return The middleName.
   */
  @java.lang.Override
  public java.lang.String getMiddleName() {
    java.lang.Object ref = middleName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      middleName_ = s;
      return s;
    }
  }
  /**
   * <code>string middleName = 6;</code>
   * @return The bytes for middleName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMiddleNameBytes() {
    java.lang.Object ref = middleName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      middleName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object lastName_;
  /**
   * <code>string lastName = 7;</code>
   * @return The lastName.
   */
  @java.lang.Override
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }
  /**
   * <code>string lastName = 7;</code>
   * @return The bytes for lastName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATEOFBIRTH_FIELD_NUMBER = 8;
  private via.sep3.group11.tier2.protobuf.GDateOfBirth dateOfBirth_;
  /**
   * <code>.GDateOfBirth dateOfBirth = 8;</code>
   * @return Whether the dateOfBirth field is set.
   */
  @java.lang.Override
  public boolean hasDateOfBirth() {
    return dateOfBirth_ != null;
  }
  /**
   * <code>.GDateOfBirth dateOfBirth = 8;</code>
   * @return The dateOfBirth.
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GDateOfBirth getDateOfBirth() {
    return dateOfBirth_ == null ? via.sep3.group11.tier2.protobuf.GDateOfBirth.getDefaultInstance() : dateOfBirth_;
  }
  /**
   * <code>.GDateOfBirth dateOfBirth = 8;</code>
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GDateOfBirthOrBuilder getDateOfBirthOrBuilder() {
    return getDateOfBirth();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gender_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nationality_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nationality_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(middleName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, middleName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, lastName_);
    }
    if (dateOfBirth_ != null) {
      output.writeMessage(8, getDateOfBirth());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gender_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nationality_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nationality_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(middleName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, middleName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, lastName_);
    }
    if (dateOfBirth_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getDateOfBirth());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.group11.tier2.protobuf.GHostDetails)) {
      return super.equals(obj);
    }
    via.sep3.group11.tier2.protobuf.GHostDetails other = (via.sep3.group11.tier2.protobuf.GHostDetails) obj;

    if (!getFirstName()
        .equals(other.getFirstName())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getGender()
        .equals(other.getGender())) return false;
    if (!getNationality()
        .equals(other.getNationality())) return false;
    if (!getMiddleName()
        .equals(other.getMiddleName())) return false;
    if (!getLastName()
        .equals(other.getLastName())) return false;
    if (hasDateOfBirth() != other.hasDateOfBirth()) return false;
    if (hasDateOfBirth()) {
      if (!getDateOfBirth()
          .equals(other.getDateOfBirth())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + getGender().hashCode();
    hash = (37 * hash) + NATIONALITY_FIELD_NUMBER;
    hash = (53 * hash) + getNationality().hashCode();
    hash = (37 * hash) + MIDDLENAME_FIELD_NUMBER;
    hash = (53 * hash) + getMiddleName().hashCode();
    hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastName().hashCode();
    if (hasDateOfBirth()) {
      hash = (37 * hash) + DATEOFBIRTH_FIELD_NUMBER;
      hash = (53 * hash) + getDateOfBirth().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.group11.tier2.protobuf.GHostDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GHostDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GHostDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GHostDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GHostDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GHostDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GHostDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GHostDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GHostDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GHostDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GHostDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GHostDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.group11.tier2.protobuf.GHostDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * -- HOST
   * </pre>
   *
   * Protobuf type {@code GHostDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GHostDetails)
      via.sep3.group11.tier2.protobuf.GHostDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GHostDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GHostDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.group11.tier2.protobuf.GHostDetails.class, via.sep3.group11.tier2.protobuf.GHostDetails.Builder.class);
    }

    // Construct using via.sep3.group11.tier2.protobuf.GHostDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      firstName_ = "";

      email_ = "";

      password_ = "";

      gender_ = "";

      nationality_ = "";

      middleName_ = "";

      lastName_ = "";

      if (dateOfBirthBuilder_ == null) {
        dateOfBirth_ = null;
      } else {
        dateOfBirth_ = null;
        dateOfBirthBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.group11.tier2.protobuf.SharedMessages.internal_static_GHostDetails_descriptor;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GHostDetails getDefaultInstanceForType() {
      return via.sep3.group11.tier2.protobuf.GHostDetails.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GHostDetails build() {
      via.sep3.group11.tier2.protobuf.GHostDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GHostDetails buildPartial() {
      via.sep3.group11.tier2.protobuf.GHostDetails result = new via.sep3.group11.tier2.protobuf.GHostDetails(this);
      result.firstName_ = firstName_;
      result.email_ = email_;
      result.password_ = password_;
      result.gender_ = gender_;
      result.nationality_ = nationality_;
      result.middleName_ = middleName_;
      result.lastName_ = lastName_;
      if (dateOfBirthBuilder_ == null) {
        result.dateOfBirth_ = dateOfBirth_;
      } else {
        result.dateOfBirth_ = dateOfBirthBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.group11.tier2.protobuf.GHostDetails) {
        return mergeFrom((via.sep3.group11.tier2.protobuf.GHostDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.group11.tier2.protobuf.GHostDetails other) {
      if (other == via.sep3.group11.tier2.protobuf.GHostDetails.getDefaultInstance()) return this;
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.getGender().isEmpty()) {
        gender_ = other.gender_;
        onChanged();
      }
      if (!other.getNationality().isEmpty()) {
        nationality_ = other.nationality_;
        onChanged();
      }
      if (!other.getMiddleName().isEmpty()) {
        middleName_ = other.middleName_;
        onChanged();
      }
      if (!other.getLastName().isEmpty()) {
        lastName_ = other.lastName_;
        onChanged();
      }
      if (other.hasDateOfBirth()) {
        mergeDateOfBirth(other.getDateOfBirth());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.group11.tier2.protobuf.GHostDetails parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.group11.tier2.protobuf.GHostDetails) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object firstName_ = "";
    /**
     * <code>string firstName = 1;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string firstName = 1;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string firstName = 1;</code>
     * @param value The firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      firstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstName() {
      
      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 1;</code>
     * @param value The bytes for firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      firstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 2;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 2;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 2;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 2;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gender_ = "";
    /**
     * <code>string gender = 4;</code>
     * @return The gender.
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gender = 4;</code>
     * @return The bytes for gender.
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gender = 4;</code>
     * @param value The gender to set.
     * @return This builder for chaining.
     */
    public Builder setGender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string gender = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGender() {
      
      gender_ = getDefaultInstance().getGender();
      onChanged();
      return this;
    }
    /**
     * <code>string gender = 4;</code>
     * @param value The bytes for gender to set.
     * @return This builder for chaining.
     */
    public Builder setGenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gender_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nationality_ = "";
    /**
     * <code>string nationality = 5;</code>
     * @return The nationality.
     */
    public java.lang.String getNationality() {
      java.lang.Object ref = nationality_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nationality_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nationality = 5;</code>
     * @return The bytes for nationality.
     */
    public com.google.protobuf.ByteString
        getNationalityBytes() {
      java.lang.Object ref = nationality_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nationality_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nationality = 5;</code>
     * @param value The nationality to set.
     * @return This builder for chaining.
     */
    public Builder setNationality(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nationality_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nationality = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNationality() {
      
      nationality_ = getDefaultInstance().getNationality();
      onChanged();
      return this;
    }
    /**
     * <code>string nationality = 5;</code>
     * @param value The bytes for nationality to set.
     * @return This builder for chaining.
     */
    public Builder setNationalityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nationality_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object middleName_ = "";
    /**
     * <code>string middleName = 6;</code>
     * @return The middleName.
     */
    public java.lang.String getMiddleName() {
      java.lang.Object ref = middleName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        middleName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string middleName = 6;</code>
     * @return The bytes for middleName.
     */
    public com.google.protobuf.ByteString
        getMiddleNameBytes() {
      java.lang.Object ref = middleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        middleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string middleName = 6;</code>
     * @param value The middleName to set.
     * @return This builder for chaining.
     */
    public Builder setMiddleName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      middleName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string middleName = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMiddleName() {
      
      middleName_ = getDefaultInstance().getMiddleName();
      onChanged();
      return this;
    }
    /**
     * <code>string middleName = 6;</code>
     * @param value The bytes for middleName to set.
     * @return This builder for chaining.
     */
    public Builder setMiddleNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      middleName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>string lastName = 7;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastName = 7;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastName = 7;</code>
     * @param value The lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastName() {
      
      lastName_ = getDefaultInstance().getLastName();
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 7;</code>
     * @param value The bytes for lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastName_ = value;
      onChanged();
      return this;
    }

    private via.sep3.group11.tier2.protobuf.GDateOfBirth dateOfBirth_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GDateOfBirth, via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder, via.sep3.group11.tier2.protobuf.GDateOfBirthOrBuilder> dateOfBirthBuilder_;
    /**
     * <code>.GDateOfBirth dateOfBirth = 8;</code>
     * @return Whether the dateOfBirth field is set.
     */
    public boolean hasDateOfBirth() {
      return dateOfBirthBuilder_ != null || dateOfBirth_ != null;
    }
    /**
     * <code>.GDateOfBirth dateOfBirth = 8;</code>
     * @return The dateOfBirth.
     */
    public via.sep3.group11.tier2.protobuf.GDateOfBirth getDateOfBirth() {
      if (dateOfBirthBuilder_ == null) {
        return dateOfBirth_ == null ? via.sep3.group11.tier2.protobuf.GDateOfBirth.getDefaultInstance() : dateOfBirth_;
      } else {
        return dateOfBirthBuilder_.getMessage();
      }
    }
    /**
     * <code>.GDateOfBirth dateOfBirth = 8;</code>
     */
    public Builder setDateOfBirth(via.sep3.group11.tier2.protobuf.GDateOfBirth value) {
      if (dateOfBirthBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateOfBirth_ = value;
        onChanged();
      } else {
        dateOfBirthBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.GDateOfBirth dateOfBirth = 8;</code>
     */
    public Builder setDateOfBirth(
        via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder builderForValue) {
      if (dateOfBirthBuilder_ == null) {
        dateOfBirth_ = builderForValue.build();
        onChanged();
      } else {
        dateOfBirthBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.GDateOfBirth dateOfBirth = 8;</code>
     */
    public Builder mergeDateOfBirth(via.sep3.group11.tier2.protobuf.GDateOfBirth value) {
      if (dateOfBirthBuilder_ == null) {
        if (dateOfBirth_ != null) {
          dateOfBirth_ =
            via.sep3.group11.tier2.protobuf.GDateOfBirth.newBuilder(dateOfBirth_).mergeFrom(value).buildPartial();
        } else {
          dateOfBirth_ = value;
        }
        onChanged();
      } else {
        dateOfBirthBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.GDateOfBirth dateOfBirth = 8;</code>
     */
    public Builder clearDateOfBirth() {
      if (dateOfBirthBuilder_ == null) {
        dateOfBirth_ = null;
        onChanged();
      } else {
        dateOfBirth_ = null;
        dateOfBirthBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.GDateOfBirth dateOfBirth = 8;</code>
     */
    public via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder getDateOfBirthBuilder() {
      
      onChanged();
      return getDateOfBirthFieldBuilder().getBuilder();
    }
    /**
     * <code>.GDateOfBirth dateOfBirth = 8;</code>
     */
    public via.sep3.group11.tier2.protobuf.GDateOfBirthOrBuilder getDateOfBirthOrBuilder() {
      if (dateOfBirthBuilder_ != null) {
        return dateOfBirthBuilder_.getMessageOrBuilder();
      } else {
        return dateOfBirth_ == null ?
            via.sep3.group11.tier2.protobuf.GDateOfBirth.getDefaultInstance() : dateOfBirth_;
      }
    }
    /**
     * <code>.GDateOfBirth dateOfBirth = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GDateOfBirth, via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder, via.sep3.group11.tier2.protobuf.GDateOfBirthOrBuilder> 
        getDateOfBirthFieldBuilder() {
      if (dateOfBirthBuilder_ == null) {
        dateOfBirthBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.group11.tier2.protobuf.GDateOfBirth, via.sep3.group11.tier2.protobuf.GDateOfBirth.Builder, via.sep3.group11.tier2.protobuf.GDateOfBirthOrBuilder>(
                getDateOfBirth(),
                getParentForChildren(),
                isClean());
        dateOfBirth_ = null;
      }
      return dateOfBirthBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GHostDetails)
  }

  // @@protoc_insertion_point(class_scope:GHostDetails)
  private static final via.sep3.group11.tier2.protobuf.GHostDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.group11.tier2.protobuf.GHostDetails();
  }

  public static via.sep3.group11.tier2.protobuf.GHostDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GHostDetails>
      PARSER = new com.google.protobuf.AbstractParser<GHostDetails>() {
    @java.lang.Override
    public GHostDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GHostDetails(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GHostDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GHostDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GHostDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

