// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Housing.proto

package via.sep3.group11.tier2.protobuf;

/**
 * Protobuf type {@code GListOfHousing}
 */
public final class GListOfHousing extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GListOfHousing)
    GListOfHousingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GListOfHousing.newBuilder() to construct.
  private GListOfHousing(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GListOfHousing() {
    housings_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GListOfHousing();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GListOfHousing(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              housings_ = new java.util.ArrayList<via.sep3.group11.tier2.protobuf.GHousingWithStatus>();
              mutable_bitField0_ |= 0x00000001;
            }
            housings_.add(
                input.readMessage(via.sep3.group11.tier2.protobuf.GHousingWithStatus.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        housings_ = java.util.Collections.unmodifiableList(housings_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.group11.tier2.protobuf.HousingOuterClass.internal_static_GListOfHousing_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.group11.tier2.protobuf.HousingOuterClass.internal_static_GListOfHousing_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.group11.tier2.protobuf.GListOfHousing.class, via.sep3.group11.tier2.protobuf.GListOfHousing.Builder.class);
  }

  public static final int HOUSINGS_FIELD_NUMBER = 1;
  private java.util.List<via.sep3.group11.tier2.protobuf.GHousingWithStatus> housings_;
  /**
   * <code>repeated .GHousingWithStatus housings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sep3.group11.tier2.protobuf.GHousingWithStatus> getHousingsList() {
    return housings_;
  }
  /**
   * <code>repeated .GHousingWithStatus housings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder> 
      getHousingsOrBuilderList() {
    return housings_;
  }
  /**
   * <code>repeated .GHousingWithStatus housings = 1;</code>
   */
  @java.lang.Override
  public int getHousingsCount() {
    return housings_.size();
  }
  /**
   * <code>repeated .GHousingWithStatus housings = 1;</code>
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GHousingWithStatus getHousings(int index) {
    return housings_.get(index);
  }
  /**
   * <code>repeated .GHousingWithStatus housings = 1;</code>
   */
  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder getHousingsOrBuilder(
      int index) {
    return housings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < housings_.size(); i++) {
      output.writeMessage(1, housings_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < housings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, housings_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.group11.tier2.protobuf.GListOfHousing)) {
      return super.equals(obj);
    }
    via.sep3.group11.tier2.protobuf.GListOfHousing other = (via.sep3.group11.tier2.protobuf.GListOfHousing) obj;

    if (!getHousingsList()
        .equals(other.getHousingsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHousingsCount() > 0) {
      hash = (37 * hash) + HOUSINGS_FIELD_NUMBER;
      hash = (53 * hash) + getHousingsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.group11.tier2.protobuf.GListOfHousing parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.group11.tier2.protobuf.GListOfHousing prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GListOfHousing}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GListOfHousing)
      via.sep3.group11.tier2.protobuf.GListOfHousingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.group11.tier2.protobuf.HousingOuterClass.internal_static_GListOfHousing_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.group11.tier2.protobuf.HousingOuterClass.internal_static_GListOfHousing_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.group11.tier2.protobuf.GListOfHousing.class, via.sep3.group11.tier2.protobuf.GListOfHousing.Builder.class);
    }

    // Construct using via.sep3.group11.tier2.protobuf.GListOfHousing.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHousingsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (housingsBuilder_ == null) {
        housings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        housingsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.group11.tier2.protobuf.HousingOuterClass.internal_static_GListOfHousing_descriptor;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GListOfHousing getDefaultInstanceForType() {
      return via.sep3.group11.tier2.protobuf.GListOfHousing.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GListOfHousing build() {
      via.sep3.group11.tier2.protobuf.GListOfHousing result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.group11.tier2.protobuf.GListOfHousing buildPartial() {
      via.sep3.group11.tier2.protobuf.GListOfHousing result = new via.sep3.group11.tier2.protobuf.GListOfHousing(this);
      int from_bitField0_ = bitField0_;
      if (housingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          housings_ = java.util.Collections.unmodifiableList(housings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.housings_ = housings_;
      } else {
        result.housings_ = housingsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.group11.tier2.protobuf.GListOfHousing) {
        return mergeFrom((via.sep3.group11.tier2.protobuf.GListOfHousing)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.group11.tier2.protobuf.GListOfHousing other) {
      if (other == via.sep3.group11.tier2.protobuf.GListOfHousing.getDefaultInstance()) return this;
      if (housingsBuilder_ == null) {
        if (!other.housings_.isEmpty()) {
          if (housings_.isEmpty()) {
            housings_ = other.housings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHousingsIsMutable();
            housings_.addAll(other.housings_);
          }
          onChanged();
        }
      } else {
        if (!other.housings_.isEmpty()) {
          if (housingsBuilder_.isEmpty()) {
            housingsBuilder_.dispose();
            housingsBuilder_ = null;
            housings_ = other.housings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            housingsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHousingsFieldBuilder() : null;
          } else {
            housingsBuilder_.addAllMessages(other.housings_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.group11.tier2.protobuf.GListOfHousing parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.group11.tier2.protobuf.GListOfHousing) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sep3.group11.tier2.protobuf.GHousingWithStatus> housings_ =
      java.util.Collections.emptyList();
    private void ensureHousingsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        housings_ = new java.util.ArrayList<via.sep3.group11.tier2.protobuf.GHousingWithStatus>(housings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GHousingWithStatus, via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder, via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder> housingsBuilder_;

    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public java.util.List<via.sep3.group11.tier2.protobuf.GHousingWithStatus> getHousingsList() {
      if (housingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(housings_);
      } else {
        return housingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public int getHousingsCount() {
      if (housingsBuilder_ == null) {
        return housings_.size();
      } else {
        return housingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GHousingWithStatus getHousings(int index) {
      if (housingsBuilder_ == null) {
        return housings_.get(index);
      } else {
        return housingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public Builder setHousings(
        int index, via.sep3.group11.tier2.protobuf.GHousingWithStatus value) {
      if (housingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHousingsIsMutable();
        housings_.set(index, value);
        onChanged();
      } else {
        housingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public Builder setHousings(
        int index, via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder builderForValue) {
      if (housingsBuilder_ == null) {
        ensureHousingsIsMutable();
        housings_.set(index, builderForValue.build());
        onChanged();
      } else {
        housingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public Builder addHousings(via.sep3.group11.tier2.protobuf.GHousingWithStatus value) {
      if (housingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHousingsIsMutable();
        housings_.add(value);
        onChanged();
      } else {
        housingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public Builder addHousings(
        int index, via.sep3.group11.tier2.protobuf.GHousingWithStatus value) {
      if (housingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHousingsIsMutable();
        housings_.add(index, value);
        onChanged();
      } else {
        housingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public Builder addHousings(
        via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder builderForValue) {
      if (housingsBuilder_ == null) {
        ensureHousingsIsMutable();
        housings_.add(builderForValue.build());
        onChanged();
      } else {
        housingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public Builder addHousings(
        int index, via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder builderForValue) {
      if (housingsBuilder_ == null) {
        ensureHousingsIsMutable();
        housings_.add(index, builderForValue.build());
        onChanged();
      } else {
        housingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public Builder addAllHousings(
        java.lang.Iterable<? extends via.sep3.group11.tier2.protobuf.GHousingWithStatus> values) {
      if (housingsBuilder_ == null) {
        ensureHousingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, housings_);
        onChanged();
      } else {
        housingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public Builder clearHousings() {
      if (housingsBuilder_ == null) {
        housings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        housingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public Builder removeHousings(int index) {
      if (housingsBuilder_ == null) {
        ensureHousingsIsMutable();
        housings_.remove(index);
        onChanged();
      } else {
        housingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder getHousingsBuilder(
        int index) {
      return getHousingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder getHousingsOrBuilder(
        int index) {
      if (housingsBuilder_ == null) {
        return housings_.get(index);  } else {
        return housingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public java.util.List<? extends via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder> 
         getHousingsOrBuilderList() {
      if (housingsBuilder_ != null) {
        return housingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(housings_);
      }
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder addHousingsBuilder() {
      return getHousingsFieldBuilder().addBuilder(
          via.sep3.group11.tier2.protobuf.GHousingWithStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder addHousingsBuilder(
        int index) {
      return getHousingsFieldBuilder().addBuilder(
          index, via.sep3.group11.tier2.protobuf.GHousingWithStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .GHousingWithStatus housings = 1;</code>
     */
    public java.util.List<via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder> 
         getHousingsBuilderList() {
      return getHousingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.group11.tier2.protobuf.GHousingWithStatus, via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder, via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder> 
        getHousingsFieldBuilder() {
      if (housingsBuilder_ == null) {
        housingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sep3.group11.tier2.protobuf.GHousingWithStatus, via.sep3.group11.tier2.protobuf.GHousingWithStatus.Builder, via.sep3.group11.tier2.protobuf.GHousingWithStatusOrBuilder>(
                housings_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        housings_ = null;
      }
      return housingsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GListOfHousing)
  }

  // @@protoc_insertion_point(class_scope:GListOfHousing)
  private static final via.sep3.group11.tier2.protobuf.GListOfHousing DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.group11.tier2.protobuf.GListOfHousing();
  }

  public static via.sep3.group11.tier2.protobuf.GListOfHousing getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GListOfHousing>
      PARSER = new com.google.protobuf.AbstractParser<GListOfHousing>() {
    @java.lang.Override
    public GListOfHousing parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GListOfHousing(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GListOfHousing> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GListOfHousing> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.group11.tier2.protobuf.GListOfHousing getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

